# Generated by Django 4.1.7 on 2023-06-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_app", "0007_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("img", models.CharField(max_length=64, verbose_name="图片")),
            ],
        ),
    ]
